In [1]:
import numpy as np

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
data = np.random.randn(7,4)
data

array([[ 0.76186972, -0.40783393, -2.00470755, -0.00407839],
       [-0.20644518, -0.01636635, -0.86176029,  0.06712283],
       [ 0.72681374,  0.85237973,  1.10912957, -0.8293339 ],
       [-0.409587  ,  0.12684794, -0.506579  ,  1.64764667],
       [ 0.31171536,  1.11467656, -0.16867144,  1.28989627],
       [ 1.80931929,  0.85621179,  0.64891591,  1.23815013],
       [ 0.42284108,  1.77275032, -0.96212018, -0.97507658]])

In [8]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [7]:
data[names=='Bob']

array([[ 0.76186972, -0.40783393, -2.00470755, -0.00407839],
       [-0.409587  ,  0.12684794, -0.506579  ,  1.64764667]])

In [9]:
data[names=='Bob',2:]

array([[-2.00470755, -0.00407839],
       [-0.506579  ,  1.64764667]])

In [10]:
data[names=='Bob',3]

array([-0.00407839,  1.64764667])

In [12]:
data[~(names=='Bob')]

array([[-0.20644518, -0.01636635, -0.86176029,  0.06712283],
       [ 0.72681374,  0.85237973,  1.10912957, -0.8293339 ],
       [ 0.31171536,  1.11467656, -0.16867144,  1.28989627],
       [ 1.80931929,  0.85621179,  0.64891591,  1.23815013],
       [ 0.42284108,  1.77275032, -0.96212018, -0.97507658]])

In [13]:
cond = names =='Bob'

In [14]:
data[~cond]

array([[-0.20644518, -0.01636635, -0.86176029,  0.06712283],
       [ 0.72681374,  0.85237973,  1.10912957, -0.8293339 ],
       [ 0.31171536,  1.11467656, -0.16867144,  1.28989627],
       [ 1.80931929,  0.85621179,  0.64891591,  1.23815013],
       [ 0.42284108,  1.77275032, -0.96212018, -0.97507658]])

In [16]:
mask = (names == 'Bob') | (names == 'Will')

In [17]:
data[mask]

array([[ 0.76186972, -0.40783393, -2.00470755, -0.00407839],
       [ 0.72681374,  0.85237973,  1.10912957, -0.8293339 ],
       [-0.409587  ,  0.12684794, -0.506579  ,  1.64764667],
       [ 0.31171536,  1.11467656, -0.16867144,  1.28989627]])

In [19]:
data[data<0] = 0
data

array([[0.76186972, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.06712283],
       [0.72681374, 0.85237973, 1.10912957, 0.        ],
       [0.        , 0.12684794, 0.        , 1.64764667],
       [0.31171536, 1.11467656, 0.        , 1.28989627],
       [1.80931929, 0.85621179, 0.64891591, 1.23815013],
       [0.42284108, 1.77275032, 0.        , 0.        ]])

In [20]:
data[~(names == 'Joe')] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.06712283],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.80931929, 0.85621179, 0.64891591, 1.23815013],
       [0.42284108, 1.77275032, 0.        , 0.        ]])

In [22]:
arr = np.zeros((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
for i in range(8):
    arr[i] = i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [25]:
arr[[4,3,0,1]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [26]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [27]:
arr[[1,5],[0,3]]

array([1., 5.])

In [28]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])