In [1]:
import numpy as np

In [4]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 23.5 ms


In [6]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 1.05 s


In [8]:
data = np.random.randn(3,2)
data

array([[-0.66071292,  3.16700467],
       [-0.38938584, -1.04661045],
       [ 1.1222183 , -1.40373075]])

In [9]:
data*10

array([[ -6.60712918,  31.67004666],
       [ -3.89385835, -10.46610448],
       [ 11.22218304, -14.03730754]])

In [10]:
data + data

array([[-1.32142584,  6.33400933],
       [-0.77877167, -2.0932209 ],
       [ 2.24443661, -2.80746151]])

In [11]:
data.shape

(3, 2)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 3)

In [18]:
arr2.dtype

dtype('int32')

In [20]:
arr_zeros = np.zeros(5)
arr_zeros

array([0., 0., 0., 0., 0.])

In [21]:
arr_zeros_1 = np.zeros((3,2))
arr_zeros_1

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
arr_zeros_2 = np.zeros((2,3,2))
arr_zeros_2

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [23]:
arr3 = np.arange(15)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr4 = np.array([1,2,3],dtype='float')
arr4

array([1., 2., 3.])

In [26]:
arr5 = np.array([1,2,3],dtype='int')
arr5

array([1, 2, 3])

In [32]:
arr6 = np.array([1,2,3,4,5,6])
print(arr6,arr6.dtype)

arr7 = arr6.astype('float')
print(arr7,arr7.dtype)

[1 2 3 4 5 6] int32
[1. 2. 3. 4. 5. 6.] float64


In [35]:
num_strings = np.array(['1.1','-2.6','12','10.5'],dtype=np.string_)
arry_num = num_strings.astype('float')
arry_num

array([ 1.1, -2.6, 12. , 10.5])

In [36]:
int_arr = np.arange(10)
calibre_arr = np.array([.22, .270, .357, .380, .44, .50],dtype='float')

int_arr = int_arr.astype(calibre_arr.dtype)
int_arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [46]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [47]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [49]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [50]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

In [51]:
arr8 = np.arange(10)
arr8[5:8]

array([5, 6, 7])

In [52]:
arr8[5:8] = 12
arr8

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [54]:
arr_slice = arr8[5:8]
arr_slice[1] = 123

arr8

array([  0,   1,   2,   3,   4,  12, 123,  12,   8,   9])

In [55]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr2d[2]

array([7, 8, 9])

In [59]:
arr2d[2][0]

7

In [61]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[1,3,5],[7,9,11]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]])

In [62]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
old_arr3d = arr3d[0].copy()
arr3d[0] = 42

In [69]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]])

In [71]:
arr3d[0] = old_arr3d
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]])

In [72]:
arr3d[1,0]

array([1, 3, 5])

In [75]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [81]:
arr2d[:2,2]

array([3, 6])

In [83]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])